spring:
  application:
    name: demo-foo
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: demo-foo
      enable-auto-commit: true
      auto-offset-reset: latest
    listener:
      concurrency: 4
