spring:
  application:
    admin:
      enabled: true
    name: demo-zuul
logging:
  level:
    root: DEBUG

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8672/eureka/
zuul:
  routes:
    demo-service-provider:
      path: /provider/**
      stripPrefix: false
      #serviceId: demo-service-provider
      #url: http://localhost:8081
ribbon:
  eureka:
    enabled: true

#demo-service-provider:
#  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    listOfServers: http://localhost:8081
#    ConnectTimeout: 1000
#    ReadTimeout: 3000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100