spring:
  application:
    admin:
      enabled: true
    name: demo-service-provider
logging:
  level:
    root: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8672/eureka/
server:
  port: 8081