spring:
  application:
    admin:
<<<<<<< HEAD
      enabled: false
=======
      enabled: true
>>>>>>> refs/remotes/origin/dev
    name: demo-service-consumer
logging:
  level:
    root: DEBUG

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8672/eureka/