spring:
  application:
    admin:
      enabled: false
    name: demo-service-consumer
logging:
  level:
    root: DEBUG
ribbon:
  eureka:
    enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8672/eureka/